name: pull request

on:
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./SimplePipelineAPI

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.x"

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./SimplePipelineAPI

      - name: Rub build
        run: dotnet build --no-restore
        working-directory: ./SimplePipelineAPI

      - name: Run tests
        run: dotnet test --no-build --verbosity normal
        working-directory: ./SimplePipelineAPI

      - name: .NET Lint
        uses: zyactions/dotnet-lint@v1
        with:
          workspace: SimplePipelineAPI/SimplePipelineAPI.csproj
          implicit-restore: true
