name: push request

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.x"

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./SimplePipelineAPI

      - name: Rub build
        run: dotnet build --no-restore
        working-directory: ./SimplePipelineAPI

      - name: Run publish
        run: dotnet publish SimplePipelineAPI.csproj -c Release -o app
        working-directory: ./SimplePipelineAPI

      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: app
          path: app
